f = input()
a = int(input())
b = int(input())
c = int(input())
print('================Чек================')
print('Товар:' + ' ' * (28 - len(f)), f)
print('Цена:' + ' ' * (18 - len(str(a) + str(b))), f'{b}кг * {a}руб/кг')
print('Итого:' + ' ' * (25 - len(str(a * b))), f'{a * b}руб')
print('Внесено:' + ' ' * (23 - len(str(c))), f'{c}руб')
print('Сдача:' + ' ' * (25 - len(str(c - a * b))), f'{c - a * b}руб')
print('===================================')
